### ISSUE TITLE
Error in value[[3L]](cond) :  

### ISSUE THREAD

**Issue by avery021** [JasperHG90/qualtRics#71]
Receiving the following error on about 7 survey IDs.

Error in value[[3L]](cond) : 
  Error extracting csv from zip file. Please re-run your query.

Found the error...It was due to a "/" in the title of the survey names.

**Comment by JasperHG90** [comment]
Thanks for this! Glad you found the error.

**Comment by ivannarodriguez** [comment]
i just encountered the same error and the survey also contains "/" in the title. how were you able to solve the error? did you rename the survey so as to not include the "/"? or how can i keep the "/" in and be able to extract the survey?

**Comment by ReinoWCC** [comment]
> 

This was helpful. I just fixed it by replacing the / in the title with -.

**Comment by jmobrien** [comment]
@ReinoWCC touching base with you since this is an old issue, and a lot of the internals of qualtRics have changed since then.  So far I can't seem to reproduce it myself, but if we're still seeing it I'd love to know what we're dealing with.

Clarifying on a couple things:
* What function was producing this error for you?  (`fetch_survey()` I'm guessing, but if not let me know)
* And It was a "/" in the name of the overall survey title producing the issue? 
* Also, what operating system are you using (Mac, Windows, or something else?)
